$LOAD_PATH.push(File.dirname(__FILE__))
require 'matrix'
require 'geom/number3d'
require 'geom/vertex3d'
require 'geom/triangle_mesh3d'
require 'geom/polygon3d'
require 'geom/triangle3d'
require 'geom/plane3d'
require 'geom/matrix3d'
require 'geom/intersection'
require 'geom/connection'
require 'geom/edge'
